[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "https://discord.gg/lol"
  status = 301

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/loader?page=admin"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://discord.gg/lol"
  status = 301
