[build]
  functions = "netlify/functions"

# Rewrite /admin to the function with ?page=admin
[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/loader?page=admin"
  status = 200
  force = true
